name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
          MYSQL_DATABASE: test_app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Grails
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install grails 4.0.12
        sdk use grails 4.0.12

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h "127.0.0.1" --silent; then
            break
          fi
          echo 'Waiting for MySQL...'
          sleep 1
        done

    - name: Run Grails tests
      env:
        GRAILS_ENV: test
        DB_URL: jdbc:mysql://localhost:3306/test_app
        DB_USERNAME: root
        DB_PASSWORD: my-secret-pw
      run: ./grailsw test-app